/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import { Inter } from 'next/font/google'
import HomePage from '@/components/Home'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>The Cappa Luxury Hotel</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
        <img className='fixed top-0 right-0 bottom-0 left-0 w-full h-[100vh] object-cover z-[1]' src='/sliders/slider2.jpeg' alt=''/>
        <HomePage/>
      </main>
    </>
  )
}
